# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Блог
url:                 http://b.ocsf.in
paginate:            3
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              kpmy
  url:               https://twitter.com/aka2538
  email:             petryxa.clever@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/kpmy/kpmy.github.io
